spring:
  cloud:
    gateway:
      routes:
        - id: after_route
          uri: http://localhost:8090
          predicates:
            - Path=/users
          filters:
            - RewritePath=/users, /user-service
            - AddRequestHeader=hello-world-header, hi!!