spring:
  cloud:
    gateway:
      routes:
      - id: users
        uri: http://localhost:8090
        predicates:
        - Path=/users
        filters:
        - AddRequestHeader=hello-header, Hello!
        - RewritePath=/users,/user-service